(library
 (name sun_cli)
 (wrapped false)
 (libraries unix yojson cmdliner otoml sun_process ptime)
 (modules
  Sun_cli_process
  Sun_cli_scaffold
  Sun_cli_scaffold_templates
  Sun_cli_workspace
  Sun_cli_manifest_yaml
  Sun_cli_manifest
  Sun_cli_config
  Sun_cli_toml
  Sun_cli_plan_ids
  Sun_cli_workspace_scan
  Sun_cli_kubernetes_name
  Sun_cli_deployment_plan
  Sun_cli_deployment_render
  Sun_cli_env_target
  Sun_cli_executor
  Sun_cli_release_inspection
  Sun_cli_secret
  Sun_cli_cmd_new
  Sun_cli_logs
  Sun_cli_deployment_state
  Sun_cli_dev_observability
  Sun_cli_state
  Sun_cli_port_forward
  Sun_cli_command_request
  Sun_cli_kubectl
  Sun_cli_rollout_diagnosis
  Sun_cli_loki
  Sun_cli_run_log
  Sun_cli_observability_url
  Sun_cli_open
  Sun_cli_status
  Sun_cli_rollback
  Sun_cli_docker
  Sun_cli_helm
  Sun_cli_terraform))
