(library
 (name sun_cli)
 (wrapped false)
 (libraries unix yojson cmdliner otoml sun_process)
 (modules
  Sun_cli_shell
  Sun_cli_scaffold
  Sun_cli_scaffold_templates
  Sun_cli_workspace
  Sun_cli_manifest
  Sun_cli_toml
  Sun_cli_deployment_plan
  Sun_cli_env_target
  Sun_cli_executor
  Sun_cli_hosted_model
  Sun_cli_release_inspection
  Sun_cli_secret
  Sun_cli_hosted_url
  Sun_cli_hosted_executor
  Sun_cli_registry
  Sun_cli_control_plane
  Sun_cli_cmd_new
  Sun_cli_logs
  Sun_cli_deployment_state
  Sun_cli_state))
