let subst = Sun_cli_scaffold.subst
let write  = Sun_cli_scaffold.write_file
let link   = Sun_cli_scaffold.link_dir
let norm   = Sun_cli_scaffold.normalize
let cap    = Sun_cli_scaffold.capitalize_name

(* ── Bundle / workspace location helpers ─────────────────────────────── *)

let is_sun_home dir =
  Sys.file_exists (Filename.concat dir "framework/sun-svc/lib/dune")
  && Sys.file_exists (Filename.concat dir "integrations/kafka/kafka-eio-service/lib/dune")

let rec realpath path =
  let path =
    if Filename.is_relative path then Filename.concat (Sys.getcwd ()) path else path
  in
  try
    let target = Unix.readlink path in
    let target =
      if Filename.is_relative target then Filename.concat (Filename.dirname path) target
      else target
    in
    realpath target
  with Unix.Unix_error ((Unix.EINVAL | Unix.ENOENT), _, _) -> path

let rec find_ancestor pred dir =
  if pred dir then Some dir
  else
    let parent = Filename.dirname dir in
    if parent = dir then None else find_ancestor pred parent

let infer_sun_home () =
  match Sys.getenv_opt "SUN_HOME" with
  | Some dir when is_sun_home dir -> Some dir
  | Some _ -> None  (* invalid SUN_HOME — NOTE in new_workspace covers this *)
  | None ->
    let exe =
      try Unix.readlink "/proc/self/exe"
      with Unix.Unix_error _ -> Sys.executable_name
    in
    find_ancestor is_sun_home (Filename.dirname (realpath exe))

let link_sun_sources workspace =
  match infer_sun_home () with
  | None -> false
  | Some sun_home ->
    link ~path:(workspace ^ "/vendor/framework")
      ~target:(Filename.concat sun_home "framework");
    link ~path:(workspace ^ "/vendor/integrations")
      ~target:(Filename.concat sun_home "integrations");
    true

(* ── Workspace-only root templates ───────────────────────────────────── *)

let tpl_ocamlformat = {tpl|profile = default
version = 0.27.0
|tpl}

let tpl_dune_project = {tpl|(lang dune 3.0)
|tpl}

let tpl_dockerignore = {tpl|_build/
.git/
*.docker-ctx/
|tpl}

(* ── Workspace demo templates ────────────────────────────────────────── *)

let ws_charged_ml = {tpl|type t = {
  id             : string;
  amount_cents   : int;
  customer_id    : string;
  currency       : string;
  correlation_id : string;
}

let topic_name = "{{name}}-payments-charges"

let schema = {|{
  "type": "object",
  "properties": {
    "id":             { "type": "string"  },
    "amount_cents":   { "type": "integer" },
    "customer_id":    { "type": "string"  },
    "currency":       { "type": "string"  },
    "correlation_id": { "type": "string"  }
  },
  "required": ["id", "amount_cents", "customer_id", "currency", "correlation_id"]
}|}

let encode t = `Assoc [
  ("id",             `String t.id);
  ("amount_cents",   `Int    t.amount_cents);
  ("customer_id",    `String t.customer_id);
  ("currency",       `String t.currency);
  ("correlation_id", `String t.correlation_id);
]

let decode = function
  | `Assoc fields ->
    let get_s k = match List.assoc_opt k fields with Some (`String s) -> Some s | _ -> None in
    let get_i k = match List.assoc_opt k fields with Some (`Int i)    -> Some i | _ -> None in
    (match get_s "id", get_i "amount_cents", get_s "customer_id",
           get_s "currency", get_s "correlation_id" with
     | Some id, Some amount_cents, Some customer_id,
       Some currency, Some correlation_id ->
       Ok { id; amount_cents; customer_id; currency; correlation_id }
     | _ -> Error "missing required fields")
  | _ -> Error "expected object"
|tpl}

let ws_events_dune = {tpl|(library
 (name {{name}}_payments_events)
 (wrapped false)
 (modules Charged)
 (libraries kafka_eio_service yojson))
|tpl}

let ws_notification_ml = {tpl|(* Notification storage — generated by sun new workspace.
   Run `sun migrate` to create the table in the cluster. *)

let insert_q =
  Caqti_request.Infix.(Caqti_type.(t4 string string int string) ->. Caqti_type.unit)
    "INSERT INTO {{name}}_notifications \
     (charge_id, customer_id, amount_cents, currency) \
     VALUES (?, ?, ?, ?)"

let list_q =
  Caqti_request.Infix.(Caqti_type.unit ->* Caqti_type.(t4 string string int string))
    "SELECT charge_id, customer_id, amount_cents, currency \
     FROM {{name}}_notifications \
     ORDER BY created_at DESC LIMIT 20"

let insert pool ~charge_id ~customer_id ~amount_cents ~currency =
  Db.exec pool insert_q (charge_id, customer_id, amount_cents, currency)

let list_recent pool =
  Db.collect pool list_q ()
|tpl}

let ws_storage_dune = {tpl|(library
 (name {{name}}_storage)
 (wrapped false)
 (modules Notification)
 (libraries sun_storage caqti))
|tpl}

let ws_svc_handler_ml = {tpl|(* POST /charges  — publish Charged to Kafka
   GET  /health      — liveness probe
   GET  /notifications — list notifications written by notify_worker *)

let routes pool ~publish_charged = [
  Route.get "/health" ~auth:`Public (fun _req ->
    Response.ok "ok"
  );
  Route.post "/charges" ~auth:`Public (fun req ->
    let j     = Yojson.Basic.from_string req.body in
    let get_s k = Yojson.Basic.Util.(j |> member k |> to_string_option
                  |> Option.value ~default:"") in
    let get_i k = Yojson.Basic.Util.(j |> member k |> to_int_option
                  |> Option.value ~default:0) in
    let charge_id = Printf.sprintf "ch_%06d" (Random.int 999999) in
    let event : Charged.t = {
      id             = charge_id;
      customer_id    = get_s "customer_id";
      amount_cents   = get_i "amount_cents";
      currency       = get_s "currency";
      correlation_id = Option.value (Request.header req "x-correlation-id")
                         ~default:charge_id;
    } in
    match publish_charged event with
    | Ok () ->
      Response.json ~status:202
        (Printf.sprintf {|{"id":"%s","accepted":true}|} charge_id)
    | Error msg ->
      Response.internal_error ("publish failed: " ^ msg)
  );
  Route.get "/notifications" ~auth:`Public (fun _req ->
    match pool with
    | None ->
      Response.json {|[]|}
    | Some p ->
      (match Notification.list_recent p with
       | Error _  -> Response.json ~status:500 {|{"error":"db unavailable"}|}
       | Ok rows  ->
         let row_json (charge_id, customer_id, amount_cents, currency) =
           `Assoc [
             ("charge_id",    `String charge_id);
             ("customer_id",  `String customer_id);
             ("amount_cents", `Int amount_cents);
             ("currency",     `String currency);
           ]
         in
         Response.json (Yojson.Basic.to_string (`List (List.map row_json rows))))
  );
]
|tpl}

let ws_svc_lib_dune = {tpl|(library
 (name {{name}}_payments_charge_svc)
 (wrapped false)
 (modules Handler)
 (libraries {{name}}_storage {{name}}_payments_events sun_svc yojson))
|tpl}

let ws_svc_bin_ml = {tpl|let () =
  let postgres_url = Option.bind (Sys.getenv_opt "POSTGRES_URL") (fun s -> if s = "" then None else Some s) in
  let loki_url     = Sys.getenv_opt "LOKI_URL" in
  let kafka_config = Kafka_service.config_of_env () in
  Eio_main.run @@ fun env ->
  let log_backend = match loki_url with
    | None     -> Obs.stdout
    | Some url ->
      Obs_loki.create ~net:env#net ~clock:env#clock ~url
        ~label_names:["service"; "team"] ()
  in
  let prom, render = Obs_prometheus.create () in
  let ot =
    Obs.with_context
      (Obs.create ~service:"{{name}}-charge-svc" ~mono_clock:env#mono_clock
         ~backend:(Obs.compose log_backend prom))
      [("team", "payments")]
  in
  Eio.Switch.run @@ fun sw ->
  let pool = match postgres_url with
    | None     -> None
    | Some url ->
      (match Db.create_pool ~url ~sw ~stdenv:(env :> Caqti_eio.stdenv) () with
       | Error _ -> None
       | Ok p    -> Some p)
  in
  let kafka =
    match Kafka_service.create kafka_config ~sw with
    | Error e -> failwith ("kafka create: " ^ e)
    | Ok svc  -> svc
  in
  let charged_topic =
    match Kafka_service.register kafka ~net:env#net ~clock:env#clock
            (module Charged) with
    | Error e -> failwith ("kafka register: " ^ e)
    | Ok t    -> t
  in
  let publish_charged event =
    match Eio.Promise.await (Kafka_service.publish kafka charged_topic event) with
    | Ok () -> Ok ()
    | Error e -> Error (Kafka_error.to_string e)
  in
  Service.run (Handler.routes pool ~publish_charged) ~env ~ot ~metrics_renderer:render ()
|tpl}

let ws_svc_bin_dune = {tpl|(executable
 (name main)
 (libraries
  {{name}}_payments_charge_svc
  sun_svc kafka_eio_service obs_eio obs_eio_loki obs_eio_prometheus
  sun_storage caqti-eio caqti-eio.unix caqti-driver-postgresql
  eio_main))
|tpl}

let ws_worker_ml = {tpl|(* Inject pool and observability handle via functor so there's no mutable state.
   Worker.Make requires module Message, group_id, and handle inside the functor. *)
module Make (Config : sig
  val pool : Db.pool option
  val ot   : Obs.t
end) = struct

  module Message = Charged

  let group_id = "{{name}}-comms-notify-worker"

  let handle (msg : Message.t) ~ack ~trace_ctx:_ =
    Obs.log_t Config.ot Obs.Info
      ~fields:[("charge_id", msg.id); ("customer_id", msg.customer_id);
               ("amount_cents", string_of_int msg.amount_cents)]
      "charge event received";
    match Config.pool with
    | None -> ack (); Ok ()
    | Some pool ->
      (match Notification.insert pool
              ~charge_id:msg.id ~customer_id:msg.customer_id
              ~amount_cents:msg.amount_cents ~currency:msg.currency with
       | Ok ()   -> ack (); Ok ()
       | Error e ->
         Obs.log_t Config.ot Obs.Error
           ~fields:[("error", Storage_error.to_string e)]
           "db insert failed";
         Error (Storage_error.to_string e))

end
|tpl}

let ws_worker_lib_dune = {tpl|(library
 (name {{name}}_comms_notify)
 (wrapped false)
 (modules Notify_worker)
 (libraries
  {{name}}_storage {{name}}_payments_events
  kafka_eio_service obs_eio sun_storage))
|tpl}

let ws_worker_bin_ml = {tpl|let () =
  let postgres_url = Option.bind (Sys.getenv_opt "POSTGRES_URL") (fun s -> if s = "" then None else Some s) in
  let loki_url     = Sys.getenv_opt "LOKI_URL" in
  let kafka_config = Kafka_service.config_of_env () in
  Eio_main.run @@ fun env ->
  let log_backend = match loki_url with
    | None     -> Obs.stdout
    | Some url ->
      Obs_loki.create ~net:env#net ~clock:env#clock ~url
        ~label_names:["service"; "team"] ()
  in
  let prom, _render = Obs_prometheus.create () in
  let ot =
    Obs.with_context
      (Obs.create ~service:"{{name}}-notify-worker" ~mono_clock:env#mono_clock
         ~backend:(Obs.compose log_backend prom))
      [("team", "comms")]
  in
  Eio.Switch.run @@ fun sw ->
  let pool = match postgres_url with
    | None     -> None
    | Some url ->
      (match Db.create_pool ~url ~sw ~stdenv:(env :> Caqti_eio.stdenv) () with
       | Error _ -> None
       | Ok p    -> Some p)
  in
  let module W = Notify_worker.Make(struct
    let pool = pool
    let ot   = ot
  end) in
  let module WR = Worker.Make(W) in
  WR.run ~env ~config:kafka_config ~ot ()
|tpl}

let ws_worker_bin_dune = {tpl|(executable
 (name main)
 (libraries
  {{name}}_comms_notify sun_worker kafka_eio_service
  obs_eio obs_eio_loki obs_eio_prometheus
  sun_storage caqti-eio caqti-eio.unix caqti-driver-postgresql
  eio_main))
|tpl}

let ws_migration_sql = {tpl|CREATE TABLE IF NOT EXISTS {{name}}_notifications (
  id           BIGSERIAL    PRIMARY KEY,
  charge_id    TEXT         NOT NULL,
  customer_id  TEXT         NOT NULL,
  amount_cents INTEGER      NOT NULL,
  currency     TEXT         NOT NULL DEFAULT 'usd',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
|tpl}

let ws_migration_down_sql = {tpl|DROP TABLE IF EXISTS {{name}}_notifications;
|tpl}

let ws_test_schemas_ml = {tpl|(* Schema backward-compatibility check — generated by sun new workspace.
   Run against a live schema registry: SCHEMA_REGISTRY_URL=http://... dune test
   If SCHEMA_REGISTRY_URL is not set the test is skipped (safe for unit CI). *)
let () =
  match Sys.getenv_opt "SCHEMA_REGISTRY_URL" with
  | None ->
    Printf.printf "SCHEMA_REGISTRY_URL not set — skipping schema compat check\n%!"
  | Some registry_url ->
    Eio_main.run (fun env ->
      match Kafka_service.Schema.check_all
              ~net:env#net
              ~clock:env#clock
              ~registry_url
              [ (module Charged) ]
      with
      | Ok () ->
        Printf.printf "schema compatibility: ok\n%!"
      | Error e ->
        Printf.eprintf "schema compatibility FAILED: %s\n%!" e;
        exit 1
    )
|tpl}

let ws_test_dune = {tpl|(executable
 (name test_schemas)
 (libraries kafka_eio_service eio_main {{name}}_payments_events))
|tpl}

(* ── new workspace command ────────────────────────────────────────────── *)

let new_workspace name =
  let name = norm name in
  if Sys.file_exists name then begin
    Printf.eprintf "error: %S already exists\n" name;
    exit 1
  end;
  Printf.printf "\nScaffolding workspace %S ...\n\n" name;
  let v = [("name", name); ("Name", cap name)] in
  write ~path:(name ^ "/.ocamlformat") ~content:tpl_ocamlformat;
  write ~path:(name ^ "/dune-project") ~content:tpl_dune_project;
  write ~path:(name ^ "/README.md")    ~content:(subst v Sun_cli_scaffold_ci.tpl_readme);
  write ~path:(name ^ "/.github/workflows/deploy.yml")
    ~content:(subst v Sun_cli_scaffold_ci.tpl_github_deploy);
  write ~path:(name ^ "/.github/workflows/sun-ci.yml")
    ~content:(subst v Sun_cli_scaffold_ci.tpl_github_ci);
  write ~path:(name ^ "/events/payments/charged.ml")       ~content:(subst v ws_charged_ml);
  write ~path:(name ^ "/events/payments/dune")             ~content:(subst v ws_events_dune);
  write ~path:(name ^ "/lib/notification.ml") ~content:(subst v ws_notification_ml);
  write ~path:(name ^ "/lib/dune")            ~content:(subst v ws_storage_dune);
  write ~path:(name ^ "/app/payments/charge_svc/lib/handler.ml")  ~content:(subst v ws_svc_handler_ml);
  write ~path:(name ^ "/app/payments/charge_svc/lib/dune")        ~content:(subst v ws_svc_lib_dune);
  write ~path:(name ^ "/app/payments/charge_svc/bin/main.ml")     ~content:(subst v ws_svc_bin_ml);
  write ~path:(name ^ "/app/payments/charge_svc/bin/dune")        ~content:(subst v ws_svc_bin_dune);
  write ~path:(name ^ "/app/payments/charge_svc/sun.toml")        ~content:Sun_cli_scaffold.tpl_sun_toml;
  write ~path:(name ^ "/app/payments/charge_svc/Dockerfile")
    ~content:(subst (v @ [
      ("repo_dir", "app/payments/charge_svc");
      ("binary",   name ^ "-charge-svc");
    ]) Sun_cli_scaffold.tpl_dockerfile);
  write ~path:(name ^ "/app/comms/notify_worker/lib/notify_worker.ml") ~content:(subst v ws_worker_ml);
  write ~path:(name ^ "/app/comms/notify_worker/lib/dune")             ~content:(subst v ws_worker_lib_dune);
  write ~path:(name ^ "/app/comms/notify_worker/bin/main.ml")          ~content:(subst v ws_worker_bin_ml);
  write ~path:(name ^ "/app/comms/notify_worker/bin/dune")             ~content:(subst v ws_worker_bin_dune);
  write ~path:(name ^ "/app/comms/notify_worker/sun.toml")             ~content:Sun_cli_scaffold.tpl_sun_toml;
  write ~path:(name ^ "/app/comms/notify_worker/Dockerfile")
    ~content:(subst (v @ [
      ("repo_dir", "app/comms/notify_worker");
      ("binary",   name ^ "-notify-worker");
    ]) Sun_cli_scaffold.tpl_dockerfile);
  write ~path:(name ^ "/.dockerignore") ~content:tpl_dockerignore;
  write ~path:(name ^ "/db/migrations/0001_notifications.sql") ~content:(subst v ws_migration_sql);
  write ~path:(name ^ "/db/migrations/0001_notifications.down.sql") ~content:(subst v ws_migration_down_sql);
  write ~path:(name ^ "/test/test_schemas.ml") ~content:(subst v ws_test_schemas_ml);
  write ~path:(name ^ "/test/dune")            ~content:(subst v ws_test_dune);
  let linked = link_sun_sources name in
  Printf.printf {|
Done. 26 files generated.

  cd %s
  eval $(opam env) && dune build   # verify the scaffold compiles
  sun dev up           # provision local k3d cluster + infra (first time ~5 min)
  sun up               # build images, push, deploy  (~1 min after first run)
  sun migrate                          # apply DB migrations
  sun status           # check pods + see port-forward hint for charge-svc

  CI/CD: set REGISTRY + REGISTRY_USER + REGISTRY_PASSWORD secrets in GitHub, then
         push to main — .github/workflows/sun-ci.yml handles build/test/deploy.
|} name;
  if not linked then
    Printf.printf {|
NOTE: Sun framework source not found — vendor/ links were not created.
  Set SUN_HOME to your Sun checkout and re-run sun new workspace, or
  create the links manually:

    export SUN_HOME=/path/to/sun
    ln -sf $SUN_HOME/framework %s/vendor/framework
    ln -sf $SUN_HOME/integrations %s/vendor/integrations

  Without these links, dune build will fail with "Library not found".
|} name name
