(** OCaml mirror of librdkafka's rd_kafka_resp_err_t.
    Internal (negative) error codes and Kafka protocol (positive) error codes
    are both represented. The full variant list is autogenerated by scripts/gen_errors.sh. *)

type t =
  (* Internal client-side errors — negative codes *)
  | Unknown
  | Offset_out_of_range
  | Invalid_msg
  | Unknown_topic_or_part
  | Invalid_msg_size
  | Leader_not_available
  | Not_leader_for_partition
  | Request_timed_out
  | Broker_not_available
  | Replica_not_available
  | Msg_size_too_large
  | Stale_ctrl_epoch
  | Offset_metadata_too_large
  | Network_exception
  | Coordinator_load_in_progress
  | Coordinator_not_available
  | Not_coordinator
  | Topic_exception
  | Record_list_too_large
  | Not_enough_replicas
  | Not_enough_replicas_after_append
  | Invalid_required_acks
  | Illegal_generation
  | Inconsistent_group_protocol
  | Invalid_group_id
  | Unknown_member_id
  | Invalid_session_timeout
  | Rebalance_in_progress
  | Invalid_commit_offset_size
  | Topic_authorization_failed
  | Group_authorization_failed
  | Cluster_authorization_failed
  | Invalid_timestamp
  | Unsupported_sasl_mechanism
  | Illegal_sasl_state
  | Unsupported_version
  | Topic_already_exists
  | Invalid_partitions
  | Invalid_replication_factor
  | Invalid_replica_assignment
  | Invalid_config
  | Not_controller
  | Invalid_request
  | Unsupported_for_message_format
  | Policy_violation
  | Out_of_order_sequence_number
  | Duplicate_sequence_number
  | Invalid_producer_epoch
  | Invalid_txn_state
  | Invalid_producer_id_mapping
  | Invalid_transaction_timeout
  | Concurrent_transactions
  | Transaction_coordinator_fenced
  | Transactional_id_authorization_failed
  | Security_disabled
  | Operation_not_attempted
  | Kafka_storage_error
  | Log_dir_not_found
  | Sasl_authentication_failed
  | Unknown_producer_id
  | Reassignment_in_progress
  | No_error
  (* Internal librdkafka errors *)
  | Begin
  | Bad_msg
  | Bad_compression
  | Destroy
  | Fail
  | Transport
  | Crit_sys_resource
  | Resolve
  | Msg_timed_out
  | Partition_eof
  | Unknown_partition
  | Fs
  | Unknown_topic
  | All_brokers_down
  | Invalid_arg
  | Timed_out
  | Queue_full
  | Isr_insuff
  | Node_update
  | Ssl
  | Wait_coord
  | Unknown_group
  | In_progress
  | Prev_in_progress
  | Existing_subscription
  | Assign_partitions
  | Revoke_partitions
  | Conflict
  | State
  | Unknown_protocol
  | Not_implemented
  | Authentication
  | No_offset
  | Outdated
  | Timed_out_queue
  | Unsupported_feature
  | Wait_cache
  | Intr
  | Key_serialization
  | Value_serialization
  | Key_deserialization
  | Value_deserialization
  | Partial
  | Read_only
  | Noent
  | Underflow
  | Invalid_type
  | Retry
  | Purge_queue
  | Purge_inflight
  | Fatal
  | Inconsistent
  | Gapless_guarantees
  | Max_poll_exceeded
  | Unknown_broker
  | Not_configured
  | Fenced
  | Application
  | Err_unknown of int

val of_int     : int -> t
val to_string  : t -> string
val is_retryable : t -> bool
val is_fatal   : t -> bool
