(* Schema backward-compatibility check — generated by sun new workspace.
   Run against a live schema registry: SCHEMA_REGISTRY_URL=http://... dune test
   If SCHEMA_REGISTRY_URL is not set the test is skipped (safe for unit CI). *)
let () =
  match Sys.getenv_opt "SCHEMA_REGISTRY_URL" with
  | None ->
    Printf.printf "SCHEMA_REGISTRY_URL not set — skipping schema compat check\n%!"
  | Some registry_url ->
    Eio_main.run (fun env ->
      match Kafka_service.Schema.check_all
              ~net:env#net
              ~clock:env#clock
              ~registry_url
              [ (module Charged) ]
      with
      | Ok () ->
        Printf.printf "schema compatibility: ok\n%!"
      | Error e ->
        Printf.eprintf "schema compatibility FAILED: %s\n%!" e;
        exit 1
    )
