(test
 (name test_dynamo_value)
 (modules test_dynamo_value)
 (libraries dynamo_eio aws-eio alcotest yojson))

(test
 (name test_dynamo_error)
 (modules test_dynamo_error)
 (libraries dynamo_eio aws-eio alcotest))

(test
 (name test_dynamo_client)
 (modules test_dynamo_client)
 (libraries dynamo_eio aws-eio alcotest yojson))

(test
 (name test_dynamo_table)
 (modules test_dynamo_table)
 (libraries dynamo_eio aws-eio alcotest))

(test
 (name test_dynamo_live)
 (modules test_dynamo_live)
 (libraries dynamo_eio aws-eio alcotest eio_main))
