(test
 (name test_kafka_service)
 (modules test_kafka_service)
 (libraries kafka_eio_service kafka_eio_core alcotest yojson uri))

(test
 (name test_kafka_service_integration)
 (modules test_kafka_service_integration)
 (libraries kafka_eio_service kafka_eio_producer kafka_eio_core kafka_test_helpers alcotest eio_main unix))
